# Generated by Django 3.2.8 on 2021-10-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('studentId', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('course', models.CharField(max_length=6)),
                ('semester', models.CharField(choices=[('1st', 'first'), ('2nd', 'second'), ('3rd', 'third'), ('4th', 'forth'), ('5nd', 'fifth'), ('6th', 'sixth'), ('7th', 'seventh'), ('8th', 'eighth')], max_length=3)),
                ('yearOfAdmission', models.DateField()),
                ('yearOfPassout', models.DateField()),
            ],
        ),
    ]
