# Generated by Django 3.2.8 on 2021-12-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentProjectData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('studentId', models.CharField(max_length=15)),
                ('projectChoose', models.CharField(choices=[('Topic1', 'topic1')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentLogin',
        ),
    ]
